server:
    applicationConnectors:
      - type: http
        port: 6363
    adminConnectors:
      - type: http
        port: 6666
logging:
    level: WARN
    loggers:
        de.whitefrog.froggy: INFO
        de.whitefrog.froggy.service.Search: DEBUG
        # debug CORS
#        org.eclipse.jetty.servlets: DEBUG
        io.dropwizard: INFO
        io.dropwizard.jersey.jackson.JsonProcessingExceptionMapper: DEBUG
        com.google.api: ERROR
    appenders:
      # console logging
      - type: console
        logFormat: '[%d] [%-5level] %logger{36} - %msg%n'